### ISSUE TITLE
Not getting webhook callback

### ISSUE THREAD

**Issue by lukasfinn** [lambdacc/cardanohook-support#1]
Submitting subscription requests return 201, however the webhook response is not received. Tried multiple working webhook listeners. Here is an example submission.

> curl 'https://api.cardanohook.net/api/v1/subscription/register-tx' -i -X PUT \
>     -H 'Content-Type: application/json' \
>     -H 'Accept: application/json' \
>     -d '{
>     "txHash" : "c463f96c9499bd1de623f2f83b44a42084120a858a560b6927bf62c2eccd3224",
>     "webhookUrl" : "https://en8n0eg0idgj.x.pipedream.net",
>     "network" : "mainnet"
> }'

HTTP/2 201 
server: nginx/1.18.0
date: Sat, 29 Oct 2022 07:30:19 GMT
content-type: application/json
vary: Origin
vary: Access-Control-Request-Method
vary: Access-Control-Request-Headers
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

{"txHash":"c463f96c9499bd1de623f2f83b44a42084120a858a560b6927bf62c2eccd3224","refId":"ad86aa2f-922a-43fe-8bbd-0c587d486fda"}

You can see request is accepted. But no webhook callback is received.

**Comment by lambdacc** [comment]
Thank you for bringing this up. The service was failing while parsing the response from koios service. The kois dependency was updated and it appears everything is back to normal. 
Just let us know if you face issues still. Closing this ticket now.
